/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create order (reserve inventory)
         * @description 価格モデル前提:
         *     - リクエストに単価は含めない
         *     - `unitPrice` / `lineAmount` / `totalAmount` はサーバ算出値を返す
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by id */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel order (release inventory) */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm payment (idempotent) */
        post: operations["confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrderRequest: {
            /** @description 顧客ID（`customers.id` の有効顧客のみ受け付ける） */
            customerId: string;
            items: components["schemas"]["CreateOrderItem"][];
        };
        CreateOrderItem: {
            sku: string;
            quantity: number;
            /** @description クライアントが注文時点で同意した単価（商品マスタ価格との照合用） */
            unitPrice: number;
        };
        CreateOrderResponse: {
            orderId: string;
            status: components["schemas"]["OrderStatus"];
            /**
             * @description 金額表示通貨（単一通貨）
             * @enum {string}
             */
            currency?: "JPY";
            /** @description 注文合計金額（サーバ算出、最小通貨単位） */
            totalAmount?: number;
        };
        ConfirmPaymentRequest: {
            orderId: string;
            amount: number;
            idempotencyKey: string;
        };
        ConfirmPaymentResponse: {
            orderId: string;
            /** @enum {string} */
            paymentStatus: "confirmed";
        };
        Order: {
            id: string;
            customerId: string;
            status: components["schemas"]["OrderStatus"];
            items: components["schemas"]["OrderItem"][];
            /**
             * @description 金額表示通貨（単一通貨）
             * @enum {string}
             */
            currency?: "JPY";
            /** @description 注文合計金額（サーバ算出、最小通貨単位） */
            totalAmount?: number;
        };
        OrderItem: {
            sku: string;
            quantity: number;
            /** @description 商品単価（商品マスタ products を決定元に設定） */
            unitPrice?: number;
            /** @description 明細金額（unitPrice * quantity） */
            lineAmount?: number;
        };
        /** @enum {string} */
        OrderStatus: "accepted" | "confirmed" | "canceled";
        Error: {
            message: string;
        };
        /**
         * @description 標準在庫モデルの在庫表現。
         *     Available は OnHand - Reserved で定義する。
         */
        InventoryBalance: {
            /** @description 実在庫（出荷確定で減算対象） */
            onHand: number;
            /** @description 引当済み在庫（注文作成で増加、キャンセル/期限切れで減少） */
            reserved: number;
            /** @description 販売可能在庫（onHand - reserved） */
            available: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrderResponse"];
                };
            };
            /** @description Invalid request (validation error, unknown customer, or inactive customer) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Price conflict (quoted unit price mismatches server-side product price) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order canceled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPaymentRequest"];
            };
        };
        responses: {
            /** @description Payment confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmPaymentResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Amount conflict (mismatch or idempotency key reused with different amount) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
